server:
  port: 8081
spring:
  datasource:
    driver-class: org.h2.Driver
    password: ''
   # url: jdbc:h2:file:/C:/Users/marcos.mol/Desktop/testes/lanches/db/db.db
    url: jdbc:h2:file:~/lanches
    username: sa
    data: classpath:data.sql
  h2:
    console:
      enable: true
      path: /h2
  jpa:
    hibernate:
      ddl-auto: create
